apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prometheus-http-api-exporter
  namespace: monitoring
  labels:
    app:  prometheus-http-api-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-http-api-exporter
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus-http-api-exporter
    spec:
      containers:
      - name:  prometheus-http-api-exporter
        image:  yuzukiko/prometheus-http-api-exporter:3324201532
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: API_LIST
          valueFrom:
            configMapKeyRef:
              name: prometheus-http-api-exporter
              key: api
        - name: DEBUG
          value: "True"
        - name: PORT
          value: "5000"
        ports:
        - name: metrics
          containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-http-api-exporter
  namespace: monitoring
spec:
  selector:
    app: prometheus-http-api-exporter
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: metrics
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-http-api-exporter
  namespace: monitoring
  labels:
    app: prometheus-http-api-exporter
data:
  api: |
    [{"name": "", "description":"", "url":"", "headers":"{}", "request_interval":10}]
